version: "3"
services:
  postgres13:
    image: postgres:13
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: "prisma"
    ports:
      - "5435:5432"
    networks:
      - databases

networks:
  databases: null
